export const UserData=[
    {
        id:1,
        month:"January",
        userGain:400,
        lost:10
    },
    {
        id:2,
        month:"February",
        userGain:600,
        lost:12
    },
    {
        id:3,
        month:'March',
        userGain:800,
        lost:14
    },
    {
        id:4,
        month:"April",
        userGain:1000,
        lost:16
    },
    {
        id:5,
        month:"May",
        userGain:1200,
        lost:18
    },
    {
        id:6,
        month:"June",
        userGain:1400,
        lost:20
    },
    {
        id:7,
        month:"July",
        userGain:1600,
        lost:22
    }
]