export const UserDataLine=[
    {
        id:1,
        month:"May1",
        userGain:1000,
        lost:10
    },
    {
        id:2,
        month:"May3",
        userGain:2000,
        lost:12
    },
    {
        id:3,
        month:'May5',
        userGain:500,
        lost:14
    },
    {
        id:4,
        month:"May7",
        userGain:400,
        lost:16
    },
    {
        id:5,
        month:"May9",
        userGain:1000,
        lost:18
    },
    {
        id:6,
        month:"May11",
        userGain:1400,
        lost:20
    },
    {
        id:7,
        month:"May13",
        userGain:1600,
        lost:22
    }
]